[package]
name = "test-cloudfile"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["fileapi", "minwinbase", "impl-default", "winnt", "handleapi"] }
